# Generated by Django 5.1.6 on 2025-02-19 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "request_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "serial_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("input_image_urls", models.TextField()),
                ("output_image_urls", models.TextField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processor.request",
                    ),
                ),
            ],
        ),
    ]
